# Test Pipeline for Azure Pipelines
# Template for Linux

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: sudo apt-get update -qq
  displayName: 'Preinstall cleanup'

- script: sudo apt-get install -y -qq cmake cpio g++ openssl wget
  displayName: 'Install prerequisites'

- script: sudo --preserve-env ./is-installers/linux/is-install.sh
  displayName: 'Install compilers'
  env:
    IS_LICENSE_DATA_LINUX: $(IS_LICENSE_DATA_LINUX)

- script: |
     source /opt/intel/bin/iccvars.sh -arch intel64 &&
     icc -v
     mkdir build; cd build &&
     FC=ifort CC=icc CXX=icpc cmake ../src
     make
     make test
  displayName: 'Attempt compile'
